services:
  server:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: z1
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
